---

- hosts: pi
  vars:
    user: pi
    repo_url: git://github.com/HumanDynamics/openbadge-hub-py.git
    dest_location: /home/{{user}}/openbadge-hub-py
  remote_user: pi

  tasks:
  - name: Installing System Packages
    apt: name={{ item }} state=present update_cache=yes
    with_items:
      - git
      - libglib2.0-dev # From bluepy
      - python-setuptools # For installing pip
      - python-pip
      - supervisor # for running the processes as deamons
      - links2 # useful when setting up a device
    become: true

  - name: Upgrade pip
    pip:
      name: pip
      extra_args: --upgrade
    become: true

  - name: Downloading git repo
    git: repo={{repo_url}}
         dest={{dest_location}}

  - name: Installing PIP Packages
    pip: requirements={{dest_location}}/src/requirements.txt
    become: true

  - name: Installing docker
    shell: curl -sSL get.docker.com | sh
    args:
      creates: /usr/bin/docker
    become: true

  - name: Installing docker-compose
    pip:
      name: docker-compose
      state: present
    become: true

  - name: Placing config file
    template:
        src=/etc/ansible/openbadge-hub-py/.env
        dest=/home/{{user}}/openbadge-hub-py/.env

  - name: Placing supervisord file for starting pulling data
    template:
        src=badge_hub.conf
        dest=/etc/supervisor/conf.d/badge_hub.conf
    become: true

  - name: restart supervisor
    service:
      name: supervisor
      state: restarted
    become: true

